### ISSUE TITLE
Cleave Applied to Pick

### ISSUE THREAD

**Issue by Draco18s** [DemoXinMC/MoreEnchants#1]
![2014-02-03_23 14 43](https://f.cloud.github.com/assets/1750680/2073217/0b02a7da-8d53-11e3-8c80-dbebf9fd63b3.png)

Running several mods, but none that should effect the enchanting system.

**Comment by DemoXinMC** [comment]
Can you give me some more information about under which circumstances this occurred?  Other mods, MoreEnchants version, source of the item/enchants, etc?

**Comment by Draco18s** [comment]
More Enchants 1.0.1
Here's the full mod list:
![capture](https://f.cloud.github.com/assets/1750680/2073256/1aa9a55c-8d54-11e3-946e-48ba78fea89a.PNG)
Artifacts is my own, and while it does listen for the interaction event with the enchantment table it doesn't mess with any of the mechanics of it (just looks for when the user uses it).

Anyway, I expended 2 levels of exp in a 0-shelf enchantment table (or at least, the shelves were blocked from contributing).  Was a normal iron pickaxe.  It was probably around midnight on the clock.

**Comment by DemoXinMC** [comment]
My real suggestion would be to update to a newer version of MoreEnchants, and disabling the new enchants if you're not a fan.  Everything is configurable, and there are some major advances in code from 1.0 to 1.2.

**Comment by Draco18s** [comment]
Ah, there's a newer version.  I downloaded this one not _that_ long ago.

**Comment by DemoXinMC** [comment]
Let me know if you have another similar problem.  Gonna close this issue in the meantime.

**Comment by Draco18s** [comment]
Ok, just got Cleave on a pickaxe again.  1.2.2

![capture](https://f.cloud.github.com/assets/1750680/2120899/c73d8e86-91c9-11e3-9b64-3b0a7fb31b05.PNG)
